### ISSUE TITLE
Magic Methods need PHP Visibility conformance (aka protected setters aren't called by magic method)

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#898]
There was recently some confusion about TList/TMap::ReadOnly being protected vs public.   I was updating the unit tests for TPriorityMap and discovered that DefaultPriority is being set as a property by magic method when it is protected.

The reason why configuration and templates can access ReadOnly when it is protected is because accessing the property is still accessible by magic methods.

Example.
```
$map = new TMap();
$map->setReadOnly(true);   // Failure due to being protected
$map->ReadOnly = true; // works because the object constructs and accesses "setReadOnly" on itself.
```

Is this something to address or not?  should it be working this way?  Or is this a feature?

Magic methods, canGetProperty, and canSetProperty would need to check the getter/setter method for public.

This is also an issue in Yii2, I think.

**Comment by ctrlaltca** [comment]
It's definitely something that's breaking basic OOP principles and should be fixed.
I'm not sure why, since we should check is_callable() it from the caller context.
The real question is: how many things will break if we fix this? :smiling_face_with_tear:

**Comment by belisoful** [comment]
I don't think this was an error that I introduced when i added behaviors to TComponent; it was something going on before that.

**Comment by belisoful** [comment]
I'm fairly certain that Yii2 has this problem too because they do a straight method_exists check as well rather than a method_exists then method-is-public check.

I'm going to make a Prado::method_exists in the base utility object that checks if the method is public and then replace `method_exists` is TComponent with `Prado::method_exists`

**Comment by belisoful** [comment]
This is a serious enough bug that I did actually report this bug to Yii as well.

I have a working solution but it doesn't fix the regression like TMap::ReadOnly and TList::ReadOnly configuration setting.  

Even when this bug is squashed, we may need to revision some elements.  Like making ReadOnly public for TList and TMap but only allowing the first set for configuration.  there would need to be a second protected "resetReadOnly" for subclasses to change ReadOnly after the first set.

this may be a big enough change to "read only" that it should only be done with community in mind.

Keep in mind that with this solution, there won't be any ReadOnly for lists until ReadOnly is made public.  

Again, maybe only the first set should be honored in public SetReadOnly?  Breaking implementations that expect it to actually do something from the subclass.

**Comment by belisoful** [comment]
Processing.  one eternity later....      Basically, turning off get-set properties for protected and private properties also turns it off for the object too.

The price of making all properties accessible by magic method to one's own class, is making them publicly available to all.  Contrary, Limiting the public to only public functions limits the class itself being able to read its own protected and private properties.

**Comment by belisoful** [comment]
Here is the function that seems to work better.  For external calls, this only allows public, for objects get/set on themselves, it allows protected and private access.  This conforms to OOP principles.  :)

```
	public static function method_exists($object_or_class, string $method): bool
	{
		if (method_exists($object_or_class, $method)) {
			$trace = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT | DEBUG_BACKTRACE_IGNORE_ARGS, 3);
			if (empty($trace[1]['object']) || empty($trace[2]['object']) || $trace[1]['object'] !== $trace[2]['object']) {
				$reflection = new \ReflectionMethod($object_or_class, $method);
				return $reflection->isPublic();
			}
			return true;
		}
		return false;
	}
```

**Comment by belisoful** [comment]
This needs unit tests....

**Comment by belisoful** [comment]
I have an idea to resolve the TList ReadOnly being protected from configuration with this correction to method visibility to conform to PHP.

Here is my thinking:
 - Make TList and TMap setReadOnly public
 - Set the default ReadOnly to null
 - Allow the first set of ReadOnly as valid (aka when null).
 - Deny all other changes to ReadOnly
    - Except when the caller object calling it is the self, child, or parent.

This solution of allowing self, child or parent to change the ReadOnly property and allow all others to set it once is what we are looking for.

The solution is based upon the latest `method_accessible` function.  they would need to retrieve the object of the caller and caller caller, similarly.

I'm thinking of putting a Prado protected method `isCallingSelf` and `isCallingSelfClass` effectively making them "can we call protected and private methods on behalf of the caller" and "can we call private methods on behalf of the caller".

The new public setReadOnly would only allow setting of ReadOnly on first set and by parents, children, and self.

this provides the wanted external functionality vs internal functionality.

**Comment by belisoful** [comment]
Also...  After sitting with method_accessible, which is a better choice, the best name is `method_visible` because this is about "PHP Visibility" of properties, methods, and constants.  I'm going to change the name again.  Thankfully it's a minor update.

**Comment by belisoful** [comment]
After a quick `grep "protected function set" -r *` there doesn't seem to be any other classes' protected setters that would be used in configuration that would be affected by the visibly change to magic methods.  TMap and TList have the one protected ReadOnly property that was being set by magic method from configuration.

There are many protected setters that should be blocked from magic method access.  So this is a very good update.  Yii team thinks this is an enhancement.  I think it's a bug that requires some enhancement.
